[package]
authors = ["Hess Lewis <hesslewis@gmail.com>"]
name = "client"
version = "0.1.0"
description = "client"
keywords = ["client", "wasm"]
edition = "2021"

[dependencies]
yew = "0.19.3"
reqwasm = "0.2"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"