[workspace]
members = [
  "server",
  "media",
  "client",
]

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = false
panic = 'abort'
rpath = false