[package]
authors = ["Hess Lewis <hesslewis@gmail.com>"]
name = "media"
version = "0.1.0"
description = "media compression and storage system"
edition = "2021"

[dependencies]
log = "0.4.14"
mime = "0.3.0"
image = "0.24.0"
imageproc = "0.22.0"
dssim-core = "3.2.1"
ffmpeg-next = "5.0.2"