//! SeaORM Entity. Generated by sea-orm-codegen 0.7.0

pub use super::media::Entity as Media;
pub use super::post::Entity as Post;
pub use super::post_page::Entity as PostPage;
pub use super::post_tag::Entity as PostTag;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
