swagger: "2.0"
info:
  title: Homebooru
  description: tagged image board focused on portability and speed
  version: 0.1.0
host: localhost:8080
basePath: /api

/posts:
  displayName: Posts
  post:
  /{postId}:
    get:
    put: